#Application Running Port
server:
  port: 5000
  error:
    include-message: always
    whitelabel:
      enabled: false

# Database Connection
spring:
  datasource:
    url: ${DB_URL}
    username: ${U_NAME}
    password: ${U_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # This property is needed so that the postgres JDBC driver can create a Lob correctly on the Java side.
        jdbc:
          lob:
            non_contextual_creation: true
      database: postgresql
      database-platform: org.hibernate.dialect.postgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: debug
