#Application Running Port
server:
  port: 5000
  error:
    include-message: always
    whitelabel:
      enabled: false
application:
  title: BiometricAttendance
  version: 1.0
# Database Connection
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6d31ecf40ce20110ee8b
            client-secret: 7983c51490efed581fc9336baef3509399441a37
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/bams
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.postgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # This property is needed so that the postgres JDBC driver can create a Lob correctly on the Java side.
        jdbc:
          lob:
            non_contextual_creation: true
      database: postgresql
#  sql:
#    init:
#      mode: always
#      continue-on-error: false
  logging:
    level:
      org:
        springframework:
          security: TRACE
        hibernate:
          SQL: debug
